name: Hello World CI

on: 
  workflow_dispatch:
   branches: [dev]

jobs:
  hello-world-job:
    runs-on: ubuntu-latest
    steps:
     - name: checkout repo
       uses: actions/checkout@v4
     - run: echo "$(cat hello-world.txt)"